### ISSUE TITLE
Tic Tac Toe: about computing the score

### ISSUE THREAD

**Issue by PaLeroy** [glouppe/info8006-introduction-to-ai#7]
There are some final states of the game that lead to different scores in my mind.
Talking about computing the score:
On one hand, using the provided function updateScore(...) , the score is computed at each step of the game and so the aligments are fixed at each play.
On the second hand, compute the score for a given state, independent of the previous actions.

As an example, a final state of a 2 10 3 game.
 
![tic tac toe](https://user-images.githubusercontent.com/27734041/33231355-73132cde-d1f4-11e7-9b6f-814c002370b4.png)

Focusing on the interesting area, the player X has done the following actions:
(avoiding other moves)
1,2
1,3
1,4 -> 1 aligment found
1,5
1,6 -> 1 aligment found
1,1
1,7

The score is then 2 but if we take the rule, and so, if we compute the score independtly of the actions, shouldn't it be 3?

**Comment by epochstamp** [comment]
You're right, according to the rule it should be 3 but since the mechanism of the score update is order-dependent with respect to move sequences ordering, it produces this effect. There is indeed a mismatch between the rule and the implementation (really sorry about that). But I'm afraid that, if I try to correct it quickly (and the deadline is only in a few days from now), the whole engine could suffers in terms of computation time and so, your agent. 

Nevertheless, I don't think the current implementation should heavily affects the quality of your approach, since it should rely on the updateScore routine for your utility function design. But if you think it could happen, you can send me an email with a description of your approach and where the updateScore routine could affect the performance of your agent. 

Samy A.

**Comment by PaLeroy** [comment]
Thank you for the reply.
I agree with you on the fact that making a correction is not possible due to the deadline.
I am not quite sure at the moment if my idea will be affected by this, i will send you an email.
